package tms.clerk;

public class Clerk {
    
    public boolean generateReport(){
        System.out.println("Report generated by the clerk ");
        return true;
    }
   
    public boolean offenceClearedByClerk(){
        System.out.println("Offence cleared by Clerk");
        return true;
    }
}
